### ISSUE TITLE
Unable to find module

### ISSUE THREAD

**Issue by jonyeezs** [mhahn/vagrant-librarian-puppet#37]
Installed librarian-puppet through my vagrant file
```
 required_plugins = %w(vagrant-puppet-install vagrant-librarian-puppet)

 required_plugins.each do |plugin|
   need_restart = false
   unless Vagrant.has_plugin? plugin
     system "vagrant plugin install #{plugin} --verbose"
     need_restart = true
   end
   exec "vagrant #{ARGV.join(' ')}" if need_restart
 end
```
In my puppetfile:
```
forge "https://forgeapi.puppetlabs.com"
mod 'chocolatey-chocolatey'
```

I get this error:
```
==> default: Installing Puppet modules in "puppet" with Librarian-Puppet...
C:/Vagrant/gems/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo_v1.rb:76:in `api_data': Unable to fin
d module 'chocolatey-chocolatey' on https://forgeapi.puppetlabs.com (Librarian::Error)
        from C:/Vagrant/gems/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo_v1.rb:22:in `get_version
s'
        from C:/Vagrant/gems/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo.rb:15:in `versions'
        from C:/Vagrant/gems/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo.rb:42:in `manifests'
        from C:/Vagrant/gems/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge.rb:152:in `manifests'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/dependency.rb:117:in `cache_manifests!'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/dependency.rb:113:in `manifests'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_de
pendency_map_find_manifests'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in s
cope_resolving_dependency'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checki
ng_manifests'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manife
sts'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolv
ing_dependency'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_depen
dency'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_
map_find_manifests'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
        from C:/Vagrant/gems/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
        from C:/Vagrant/gems/gems/vagrant-librarian-puppet-0.8.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb
:63:in `provision'
        from C:/Vagrant/gems/gems/vagrant-librarian-puppet-0.8.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb
:29:in `block in call'
        from C:/Vagrant/gems/gems/vagrant-librarian-puppet-0.8.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb
:28:in `each'
        from C:/Vagrant/gems/gems/vagrant-librarian-puppet-0.8.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb
:28:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize
_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize
_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:86:in `call
'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize
_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `
call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'

        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/action/check_enabled.rb:18:i
n `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) i
n run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in cr
eate_with_logging_context'
```

My vagrant plugin list:
```
vagrant-librarian-puppet (0.8.0
vagrant-puppet-install (2.7.0)
vagrant-share (1.1.3, system)
```

**Comment by AwaNoodle** [comment]
Tried switching to https://forge.puppetlabs.com?
