### ISSUE TITLE
facter-1.7.6: "cannot load such file -- win32/dir" - Windows 10

### ISSUE THREAD

**Issue by fernandoluizjr** [mhahn/vagrant-librarian-puppet#44]
Hi, I have tried to install the librarian-puppet but I got this error when I bring up my vagrant machine:

```
Bringing machine 'db' up with 'virtualbox' provider...
==> db: Checking if box 'hashicorp/precise64' is up to date...
==> db: Installing Puppet modules in "librarian" with Librarian-Puppet...
Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 1920 exit 1
C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/config.rb:47:in `require': cannot load such file -- win32/dir (LoadError)
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/config.rb:47:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/resolution.rb:7:in `require'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/resolution.rb:7:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fact.rb:2:in `require'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fact.rb:2:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:in `require'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:in `<module:Facter>'
        from C:/Users/ferna/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:19:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in `require'
        from C:/Users/ferna/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:12:in `require'
        from C:/Users/ferna/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/command_line.rb:12:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `require'
        from C:/Users/ferna/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `<top (required)>'
        from C:/Users/ferna/.vagrant.d/gems/bin/puppet:23:in `load'
        from C:/Users/ferna/.vagrant.d/gems/bin/puppet:23:in `<main>'
```

I'm using Windows 10 64bits, with vagrant 1.7.4. Also I don't have the ruby and devkit installed. I mean that vagrant uses the embedded ruby and devkit.

Is there anyone that faces this problem? Is there a fix for it?

**Comment by fernandoluizjr** [comment]
I find out that is better install plugins using shell instead this lib on Windows. Closing.
