### ISSUE TITLE
Cannot install puppetlabs-vcsrepo

### ISSUE THREAD

**Issue by fculpo** [mhahn/vagrant-librarian-puppet#48]
Every time i try to install puppetlabs-vcsrepo, i encounter this error (all other modules work fine):

```
E:/Workspace/_VagrantHome/gems/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:129:in `rescue in cache_version_unpacked!': Error executin
g puppet module install. Check that this command succeeds: (Librarian::Error)
puppet module install --version 1.3.1 --target-dir E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/pup
petlabs-vcsrepo/1.3.1 --module_repository https://forgeapi.puppetlabs.com --modulepath E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/pupp
et/forge/forgeapi_puppetlabs_com/puppetlabs-vcsrepo/1.3.1 --module_working_dir E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge
/forgeapi_puppetlabs_com/puppetlabs-vcsrepo/1.3.1 --ignore-dependencies puppetlabs-vcsrepo
Error:
Error: No such file or directory @ rb_sysopen - E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppet
labs-vcsrepo/1.3.1/cache/tmp20160121-18160-1k17q6e/puppetlabs-vcsrepo-1.3.1/spec/acceptance/beaker/git/tag_checkout/negative/tag_checkout_not_exists.rb
```

Puppetfile
=======================

forge "https://forge.puppetlabs.com"

mod 'puppetlabs-apt'
mod 'puppetlabs-concat'
mod 'puppetlabs-git'
mod 'puppetlabs-inifile'
mod 'puppetlabs-ntp'
mod 'puppetlabs-stdlib'
mod 'puppetlabs/vcsrepo', "1.3.1"

mod 'saz-timezone'
mod 'camptocamp-systemd'
mod 'mayflower-php'
mod 'jfryman-nginx'

Puppetfile.lock
========================

FORGE
  remote: https://forgeapi.puppetlabs.com
  specs:
    camptocamp-systemd (0.2.2)
    darin-zypprepo (1.0.2)
    example42-puppi (2.1.12)
    example42-yum (2.1.25)
      example42-puppi (>= 2.0.0)
    jfryman-nginx (0.2.7)
      puppetlabs-apt (< 3.0.0, >= 1.8.0)
      puppetlabs-concat (< 2.0.0, >= 1.1.1)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)
    mayflower-php (3.4.2)
      darin-zypprepo (~> 1.0)
      example42-yum (~> 2.0)
      puppetlabs-apt (< 3.0.0, >= 1.0.0)
      puppetlabs-inifile (~> 1.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)
    puppetlabs-apt (2.2.1)
      puppetlabs-stdlib (< 5.0.0, >= 4.5.0)
    puppetlabs-concat (1.2.5)
      puppetlabs-stdlib (< 5.0.0, >= 3.2.0)
    puppetlabs-git (0.4.0)
      puppetlabs-stdlib (>= 3.2.0)
    puppetlabs-inifile (1.4.3)
    puppetlabs-ntp (4.1.2)
      puppetlabs-stdlib (< 5.0.0, >= 4.6.0)
    puppetlabs-stdlib (4.11.0)
    puppetlabs-vcsrepo (1.3.1)
    saz-timezone (3.3.0)
      puppetlabs-stdlib (>= 2.3.0)

DEPENDENCIES
  camptocamp-systemd (>= 0)
  jfryman-nginx (>= 0)
  mayflower-php (>= 0)
  puppetlabs-apt (>= 0)
  puppetlabs-concat (>= 0)
  puppetlabs-git (>= 0)
  puppetlabs-inifile (>= 0)
  puppetlabs-ntp (>= 0)
  puppetlabs-stdlib (>= 0)
  puppetlabs-vcsrepo (= 1.3.1)
  saz-timezone (>= 0)

Stack trace
===============================

```
E:\Workspace\bath\vagrant-puppet [master +2 ~2 -0 !]> vagrant up centos
Bringing machine 'centos' up with 'virtualbox' provider...
==> centos: vagrant-r10k not configured; skipping
==> centos: Importing base box 'boxcutter/centos71'...
==> centos: Matching MAC address for NAT networking...
==> centos: Checking if box 'boxcutter/centos71' is up to date...
==> centos: Setting the name of the VM: vagrant-puppet_centos_1453396656931_23202
==> centos: vagrant-r10k not configured; skipping
==> centos: vagrant-r10k not configured; skipping
==> centos: Installing Puppet modules with Librarian-Puppet...
==> centos: vagrant-r10k not configured; skipping
==> centos: Destroying VM and associated drives...
E:/Workspace/_VagrantHome/gems/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:129:in `rescue in cache_version_unpacked!': Error executin
g puppet module install. Check that this command succeeds: (Librarian::Error)
puppet module install --version 1.3.1 --target-dir E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/pup
petlabs-vcsrepo/1.3.1 --module_repository https://forgeapi.puppetlabs.com --modulepath E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/pupp
et/forge/forgeapi_puppetlabs_com/puppetlabs-vcsrepo/1.3.1 --module_working_dir E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge
/forgeapi_puppetlabs_com/puppetlabs-vcsrepo/1.3.1 --ignore-dependencies puppetlabs-vcsrepo
Error:
Error: No such file or directory @ rb_sysopen - E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppet
labs-vcsrepo/1.3.1/cache/tmp20160121-18160-1k17q6e/puppetlabs-vcsrepo-1.3.1/spec/acceptance/beaker/git/tag_checkout/negative/tag_checkout_not_exists.rb
Error: Try 'puppet help module install' for usage
        from E:/Workspace/_VagrantHome/gems/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:114:in `cache_version_unpacked!'
        from E:/Workspace/_VagrantHome/gems/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:56:in `install_version!'
        from E:/Workspace/_VagrantHome/gems/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge.rb:114:in `install!'
        from E:/Workspace/_VagrantHome/gems/gems/librarianp-0.6.3/lib/librarian/manifest.rb:73:in `install!'
        from E:/Workspace/_VagrantHome/gems/gems/librarianp-0.6.3/lib/librarian/action/install.rb:49:in `block in install_manifests'
        from E:/Workspace/_VagrantHome/gems/gems/librarianp-0.6.3/lib/librarian/action/install.rb:48:in `each'
        from E:/Workspace/_VagrantHome/gems/gems/librarianp-0.6.3/lib/librarian/action/install.rb:48:in `install_manifests'
        from E:/Workspace/_VagrantHome/gems/gems/librarianp-0.6.3/lib/librarian/action/install.rb:39:in `perform_installation'
        from E:/Workspace/_VagrantHome/gems/gems/librarianp-0.6.3/lib/librarian/action/install.rb:12:in `run'
        from E:/Workspace/_VagrantHome/gems/gems/vagrant-librarian-puppet-0.6.0/lib/vagrant-librarian-puppet/action/librarian_puppet.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from E:/Workspace/_VagrantHome/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from E:/Workspace/_VagrantHome/gems/gems/vagrant-r10k-0.4.1/lib/vagrant-r10k/action/deploy.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from E:/Workspace/_VagrantHome/gems/gems/vagrant-r10k-0.4.1/lib/vagrant-r10k/action/validate.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/import.rb:74:in `import'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/import.rb:13:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from E:/Workspace/_VagrantHome/gems/gems/vagrant-r10k-0.4.1/lib/vagrant-r10k/action/validate.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by jhoblitt** [comment]
Did the manual command succeed?

```
puppet module install --version 1.3.1 --target-dir E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/pup
petlabs-vcsrepo/1.3.1 --module_repository https://forgeapi.puppetlabs.com --modulepath E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/pupp
et/forge/forgeapi_puppetlabs_com/puppetlabs-vcsrepo/1.3.1 --module_working_dir E:/Workspace/bath/vagrant-puppet/puppet/.tmp/librarian/cache/source/puppet/forge
/forgeapi_puppetlabs_com/puppetlabs-vcsrepo/1.3.1 --ignore-dependencies puppetlabs-vcsrepo
```

**Comment by Ajedi32** [comment]
I'm getting this error as well. Running the command manually fails:

```
$ puppet module install --version 4.12.0 --target-dir C:/Users/ajedi32/Workspace/projects/mymodule/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.12.0 --module_repository https://forgeapi.puppetlabs.com --modulepath C:/Users/ajedi32/Workspace/projects/mymodule/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.12.0 --module_working_dir C:/Users/ajedi32/Workspace/projects/mymodule/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.12.0 --ignore-dependencies puppetlabs-stdlib
Notice: Preparing to install into C:/Users/ajedi32/Workspace/projects/mymodule/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/
4.12.0 ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: No such file or directory @ rb_sysopen - C:/Users/ajedi32/Workspace/projects/mymodule/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.12.0/cache/tmp20160613-6380-15m8v7t/puppetlabs-stdlib-4.12.0/spec/unit/puppet/parser/functions/is_absolute_path_spec.rb
```

My guess is it's caused by [the maximum path length of 260 characters in the Windows API](http://stackoverflow.com/q/1880321/1157054), as both the path in both my error message and @fculpo exceed 260 characters.

**Comment by jhoblitt** [comment]
Could you try running librarian-puppet locally with the same Puppetfile?

**Comment by Ajedi32** [comment]
You mean manually? Actually that's what I _have_ been doing. I literally _just_ discovered `vagrant-librarian-puppet` when I encountered this issue in a Google search. The issue appears to be with `librarian-puppet` itself, not `vagrant-librarian-puppet`. See voxpupuli/librarian-puppet#17...

**Comment by jhoblitt** [comment]
That's what I assumed.  I just wanted to make sure that it was an upstream problem.  Thanks.
