### ISSUE TITLE
Strange plugin failure on Windows

### ISSUE THREAD

**Issue by ringods** [mhahn/vagrant-librarian-puppet#6]
Hello,

I've got a new portable at the office, running Windows 7 Enterprise, that I tried to setup yesterday. I failed to setup a succesful combination of Vagrant+vagrant-librarian-puppet+Puppet though.

On this new machine, I started of with Vagrant 1.4.3, vagrant-librarian-puppet 0.5.0 which installed librarian-puppet 0.9.13. Alongside it, I installed Puppet 3.4.3 via the Windows MSI installer.

While puppet is in the `PATH` and can be started on the command line, running `vagrant up` results in this:

```
C:\Code\TestProject>vagrant up
Vagrant failed to initialize at a very early stage:

Failed to load the "vagrant-librarian-puppet" plugin. The output from loading
the plugin is shown below. View the logs for complete details.

stdout: 

stderr: Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
puppet --version returned 1
```

After some investigation, I [patched librarian-puppet](https://github.com/rodjek/librarian-puppet/blob/master/lib/librarian/puppet.rb#L11) to also display the error output stream when running `puppet --version`:

```
C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- win32/dir (LoadError)
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/facter/lib/facter/util/config.rb:47:in `<top (required)>'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/facter/lib/facter/util/resolution.rb:7:in `<top (required)>'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/facter/lib/facter/util/fact.rb:2:in `<top (required)>'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/facter/lib/facter.rb:23:in `<module:Facter>'
        from C:/Tools/Puppet/facter/lib/facter.rb:19:in `<top (required)>'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/puppet/lib/puppet.rb:6:in `<top (required)>'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/puppet/lib/puppet/util/command_line.rb:12:in `<top (required)>'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/sys/ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from C:/Tools/Puppet/puppet/bin/puppet:3:in `<main>'
```

So I assumed librarian-puppet was the culprit. Running librarian-puppet standalone however worked flawlessly. Only when running combined with the plugin under Vagrant, it fails to load the `win32/dir` module.

Since I installed on a new machine, I had different versions than on my old machine, so I started experimenting with downgrading to the exact versions as on my previous setup:
- Puppet from 3.4.3 to 3.3.1
- vagrant-librarian-puppet from 0.5.0 over 0.4.0, 0.3.1 to 0.3.0
- Vagrant from 1.4.3 to 1.4.0

None of these combinations resolved the issue. While it's probably something specific to my setup, I'm out of ideas. Some help would be appreciated!

**Comment by mathis-gerlach** [comment]
I have this strange behaviour with current Vagrant Version 1.7.2 on a Windows 7 64bit version. I already tried using Ruby 2.2.2 & 2.0 also 32bit and 64bit. But still it can't load gem 'win32-dir'. Is it possible to force vagrant to use Facter v2 instead from embedded folder where 1.7.6 is installed?

**Comment by jeff1evesque** [comment]
I have a similar error on Windows 7 64bit (host):

```bash
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running triggers before up...
==> default: Executing command "mkdir -p puppet/modules"...
==> default: Command execution finished.
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: machine-learning_default_1435413754720_
51349
==> default: Clearing any previously set forwarded ports...
==> default: Installing Puppet modules in "puppet" with Librarian-Puppet...
Unable to load puppet. Please install it using native packages for your platform
 (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 4164 exit 1
C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/config.rb:47:in
`require': cannot load such file -- win32/dir (LoadError)
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/con
fig.rb:47:in `<top (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/res
olution.rb:7:in `require'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/res
olution.rb:7:in `<top (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fac
t.rb:2:in `require'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter/util/fac
t.rb:2:in `<top (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:in
 `require'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:23:in
 `<module:Facter>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/facter-1.7.6/lib/facter.rb:19:in
 `<top (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in
`require'
        from C:/Users/Jeff/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet.rb:6:in
`<top (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/com
mand_line.rb:12:in `require'
        from C:/Users/Jeff/.vagrant.d/gems/gems/puppet-3.4.3/lib/puppet/util/com
mand_line.rb:12:in `<top (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `re
quire'
        from C:/Users/Jeff/.vagrant.d/gems/gems/puppet-3.4.3/bin/puppet:3:in `<t
op (required)>'
        from C:/Users/Jeff/.vagrant.d/gems/bin/puppet:23:in `load'
        from C:/Users/Jeff/.vagrant.d/gems/bin/puppet:23:in `<main>'
```
